apiVersion: v1
kind: Pod
metadata:
  name: results-access
  namespace: NAMESPACE_PLACEHOLDER
spec:
  containers:
    - name: accessor
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: results
          mountPath: /results
  volumes:
    - name: results
      persistentVolumeClaim:
        claimName: quickdraw-results-pvc
  restartPolicy: Never
